version: '3.8'

services:
# 1. KONTAINER WEB SERVER (PHP + APACHE)
  webserver:
    image: php:8.1-apache
    container_name: crossPlay_webserver
    command: bash -c "a2enmod rewrite && sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf && docker-php-ext-install mysqli && apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - crossPlay_network

  # 2. KONTAINER DATABASE (MYSQL)
  db:
    image: mysql:8.0
    container_name: crossPlay_db

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crossplay # Sesuaikan dengan nama databasemu yang dulu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - crossPlay_network

  # 3. KONTAINER PHPMYADMIN (AGAR TETAP BISA AKSES VIA BROWSER)
  phpmyadmin: 
    image: phpmyadmin:latest
    container_name: crossPlay_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80" # Akses phpMyAdmin nanti lewat localhost:8081
    networks:
      - crossPlay_network

volumes:
  mysql_data:

networks:
  crossPlay_network:
    driver: bridge